// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package Database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Target struct {
	ID              pgtype.UUID
	Url             string
	Name            pgtype.Text
	Environment     string
	IntervalSeconds int32
	TimeoutSeconds  int32
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type UptimeLog struct {
	ID           int64
	TargetID     pgtype.UUID
	StatusCode   pgtype.Int4
	LatencyMs    int32
	IsHealthy    bool
	ErrorMessage pgtype.Text
	CheckedAt    pgtype.Timestamptz
}
