// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Queries.sql

package Database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTarget = `-- name: CreateTarget :one
INSERT INTO targets (url, environment, interval_seconds, timeout_seconds)
VALUES ($1, $2, $3, $4)
RETURNING id, url, environment, interval_seconds, timeout_seconds, is_active, created_at, updated_at
`

type CreateTargetParams struct {
	Url             string
	Environment     string
	IntervalSeconds int32
	TimeoutSeconds  int32
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, createTarget,
		arg.Url,
		arg.Environment,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Environment,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTargetStats = `-- name: GetTargetStats :many
SELECT status_code, is_healthy, latency_ms, checked_at
FROM uptime_logs
WHERE target_id = $1
ORDER BY checked_at DESC
LIMIT $2
`

type GetTargetStatsParams struct {
	TargetID pgtype.UUID
	Limit    int32
}

type GetTargetStatsRow struct {
	StatusCode pgtype.Int4
	IsHealthy  bool
	LatencyMs  int32
	CheckedAt  pgtype.Timestamptz
}

func (q *Queries) GetTargetStats(ctx context.Context, arg GetTargetStatsParams) ([]GetTargetStatsRow, error) {
	rows, err := q.db.Query(ctx, getTargetStats, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTargetStatsRow
	for rows.Next() {
		var i GetTargetStatsRow
		if err := rows.Scan(
			&i.StatusCode,
			&i.IsHealthy,
			&i.LatencyMs,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUptimeLog = `-- name: InsertUptimeLog :one
INSERT INTO uptime_logs (target_id, status_code, latency_ms, is_healthy, error_message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, target_id, status_code, latency_ms, is_healthy, error_message, checked_at
`

type InsertUptimeLogParams struct {
	TargetID     pgtype.UUID
	StatusCode   pgtype.Int4
	LatencyMs    int32
	IsHealthy    bool
	ErrorMessage pgtype.Text
}

func (q *Queries) InsertUptimeLog(ctx context.Context, arg InsertUptimeLogParams) (UptimeLog, error) {
	row := q.db.QueryRow(ctx, insertUptimeLog,
		arg.TargetID,
		arg.StatusCode,
		arg.LatencyMs,
		arg.IsHealthy,
		arg.ErrorMessage,
	)
	var i UptimeLog
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.StatusCode,
		&i.LatencyMs,
		&i.IsHealthy,
		&i.ErrorMessage,
		&i.CheckedAt,
	)
	return i, err
}

const listActiveTargets = `-- name: ListActiveTargets :many
SELECT id, url, environment, interval_seconds, timeout_seconds, is_active, created_at, updated_at FROM targets
WHERE is_active = TRUE
`

func (q *Queries) ListActiveTargets(ctx context.Context) ([]Target, error) {
	rows, err := q.db.Query(ctx, listActiveTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Environment,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
