// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Queries.sql

package Database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTarget = `-- name: CreateTarget :one
INSERT INTO targets (url, name, environment, interval_seconds, timeout_seconds)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, url, name, environment, interval_seconds, timeout_seconds, is_active, created_at, updated_at
`

type CreateTargetParams struct {
	Url             string
	Name            string
	Environment     string
	IntervalSeconds int32
	TimeoutSeconds  int32
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, createTarget,
		arg.Url,
		arg.Name,
		arg.Environment,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.Environment,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTargetStatsByURLorName = `-- name: GetTargetStatsByURLorName :many
SELECT
    t.name as target_name,
    t.url as target_url,
    l.status_code,
    l.is_healthy,
    l.latency_ms,
    l.checked_at
FROM uptime_logs l
         INNER JOIN targets t ON l.target_id = t.id
WHERE t.name ILIKE $1 OR t.url ILIKE $2
ORDER BY l.checked_at DESC
LIMIT $3
`

type GetTargetStatsByURLorNameParams struct {
	Name  string
	Url   string
	Limit int32
}

type GetTargetStatsByURLorNameRow struct {
	TargetName pgtype.Text
	TargetUrl  string
	StatusCode pgtype.Int4
	IsHealthy  bool
	LatencyMs  int32
	CheckedAt  pgtype.Timestamptz
}

func (q *Queries) GetTargetStatsByURLorName(ctx context.Context, arg GetTargetStatsByURLorNameParams) ([]GetTargetStatsByURLorNameRow, error) {
	rows, err := q.db.Query(ctx, getTargetStatsByURLorName, arg.Name, arg.Url, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTargetStatsByURLorNameRow
	for rows.Next() {
		var i GetTargetStatsByURLorNameRow
		if err := rows.Scan(
			&i.TargetName,
			&i.TargetUrl,
			&i.StatusCode,
			&i.IsHealthy,
			&i.LatencyMs,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUptimeLog = `-- name: InsertUptimeLog :one
INSERT INTO uptime_logs (target_id, status_code, latency_ms, is_healthy, error_message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, target_id, status_code, latency_ms, is_healthy, error_message, checked_at
`

type InsertUptimeLogParams struct {
	TargetID     pgtype.UUID
	StatusCode   pgtype.Int4
	LatencyMs    int32
	IsHealthy    bool
	ErrorMessage pgtype.Text
}

func (q *Queries) InsertUptimeLog(ctx context.Context, arg InsertUptimeLogParams) (UptimeLog, error) {
	row := q.db.QueryRow(ctx, insertUptimeLog,
		arg.TargetID,
		arg.StatusCode,
		arg.LatencyMs,
		arg.IsHealthy,
		arg.ErrorMessage,
	)
	var i UptimeLog
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.StatusCode,
		&i.LatencyMs,
		&i.IsHealthy,
		&i.ErrorMessage,
		&i.CheckedAt,
	)
	return i, err
}

const listActiveTargets = `-- name: ListActiveTargets :many
SELECT id, url, name, environment, interval_seconds, timeout_seconds, is_active, created_at, updated_at FROM targets
WHERE is_active = TRUE
`

func (q *Queries) ListActiveTargets(ctx context.Context) ([]Target, error) {
	rows, err := q.db.Query(ctx, listActiveTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.Environment,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
